spring:
  data:
    redis:
      password: redispassword
      sentinel:
        master: mymaster
        nodes: redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

logging:
  level:
    redis.clients: DEBUG